# Generated by Django 4.2.10 on 2024-02-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Despesas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("vencimento", models.DateField(verbose_name="Vencimento")),
                ("repete", models.BooleanField(default=False, verbose_name="Repete")),
                (
                    "repeticao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Por quantos meses?"
                    ),
                ),
                ("paga", models.BooleanField(default=False, verbose_name="Paga")),
                (
                    "campo_temporario",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas_mensais",
                        to="core.despesas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
            },
        ),
    ]
